" load defaults
unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" spaces are better than tabs
set expandtab
set shiftwidth=4
set softtabstop=4
" but in case we see tabs, treat them as wide as 4 spaces
set tabstop=4

" base16-solarized-dark theme, should allow other base16 themes from terminal
" to propagate
syntax enable
set background=dark
colorscheme base16-solarized-dark
